### ISSUE TITLE
https://stellar-framework.com/ home page

### ISSUE THREAD

**Issue by siliconforks** [StellarFw/stellar-framework.com#14]
Is there a way to edit the current stellar-framework.com home page?  (The one with the mailing list signup form.)

I would revise the text as follows:

Stellar is a framework for developing Web APIs easily.  Stellar was created to address the main flaws of current frameworks, using a new paradigm to facilitate maintenance, scalability, and performance.

Stellar is an action-based web framework which includes a set of tools that make it easy to quickly prototype your new Web API and then scale it to enterprise level.

**Comment by gil0mendes** [comment]
No, that page will be replaced with this website, but I will make the changes manually. 👍

**Comment by gil0mendes** [comment]
Done!
