### ISSUE TITLE
stellar startCluster vs. stellar cluster

### ISSUE THREAD

**Issue by siliconforks** [StellarFw/stellar-framework.com#5]
The documentation talks about the `stellar startCluster` command (this is the case for both the English and Portuguese versions) but the actual command seems to be `stellar cluster`.  I'm not sure if the documentation should be fixed to match the command or the command should be fixed to match the documentation.

**Comment by gil0mendes** [comment]
The correct name is `startCluster`, I will fix the command name on the next set of fixes. Tks 😉
