### ISSUE TITLE
stellar generateEvent command

### ISSUE THREAD

**Issue by siliconforks** [StellarFw/stellar-framework.com#7]
In events.md - it mentions a `stellar generateEvent` command but the `stellar` tool doesn't seem to support this at all:

```
$ stellar --help
> Stellar Framework version 1.0.1

Available commands:
 makeAction               Create a new action file
 makeModel                Create a new model
 makeTask                 Create a new task
 run                      Run a Stellar instance
 cluster                  Create a custer
 init                     Create a new Stellar project
 help                     show the command description
```

It seems like it would probably be `stellar makeEvent` for consistency with the other commands, but that doesn't seem to exist either.

This issue is in both the English and Portuguese versions of the documentation.

**Comment by gil0mendes** [comment]
I completely forget implementing that command, I open an issue on the framework repository to fix that. The correct name must be `makeListener` one time the current directory in use to map the listeners is called `listeners`.

One more time a really apreciate or work! 👏
